languageCode = "en-us"
title = "Navin Chandradat"
baseurl = "/"
theme = "aerial"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
  name = "Navin Chandradat"
  about = "Sports Analytics &nbsp;&bull;&nbsp; Data Science &nbsp;&bull;&nbsp; Finance"
  copyright = "&copy; 2020 Navin Chandradat"
  #Disable the scrolling background by entering any string for bg_scroll. Enable by leaving bg_scroll empty.
  bg_scroll = ""
  favicon = "favicon.ico"

[[params.social]]
  medium = "Twitter"
  icon = "twitter"
  link = "#"

[[params.social]]
  medium = "Facebook"
  icon = "facebook"
  link = "#"

[[params.social]]
  medium = "Dribbble"
  icon = "dribbble"
  link = "#"

[[params.social]]
  medium = "Github"
  icon = "github"
  link = "#"

[[params.social]]
  medium = "Email"
  icon = "envelope-o"
  link = "#"
